language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
env:
  - REDMINE_VERSION=3.4.6 VERBOSE=yes
  - REDMINE_VERSION=3.3.8 VERBOSE=yes
matrix:
  exclude:
  - rvm: 2.4
    env: REDMINE_VERSION=3.3.7 VERBOSE=yes
install:
  - true
script:
  - export PLUGIN=redmine_auto_assign_group
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
