language: ruby
before_install:
  - BUNDLER_VER=`bundle --version`
  - if [[ ${BUNDLER_VER} =~ ^Bundler\ version\ 2.*$ ]]; then rvm @global do gem install bundler -v '< 2.0.0'; fi
  - if [[ ${BUNDLER_VER} =~ ^Bundler\ version\ 2.*$ ]]; then rvm @global do gem uninstall bundler -a -x -v '>= 2.0.0'; fi
  - bundle --version
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
env:
  - REDMINE_VERSION=master VERBOSE=yes
  - REDMINE_VERSION=4.0.0 VERBOSE=yes
  - REDMINE_VERSION=3.4.7 VERBOSE=yes
  - REDMINE_VERSION=3.3.9 VERBOSE=yes
matrix:
  exclude:
  - rvm: 2.5
    env: REDMINE_VERSION=3.4.7 VERBOSE=yes
    env: REDMINE_VERSION=3.3.9 VERBOSE=yes
  - rvm: 2.4
    env: REDMINE_VERSION=3.3.8 VERBOSE=yes
install:
  - true
script:
  - export PLUGIN=redmine_auto_assign_group
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
