name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * *' # JST 5:00 test3

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redmine:
          - v4.1.0
        ruby:
          - v2.6
        database:
          - postgresql
          - mysql
          - sqlite3

    steps:
      - name: Redmine plugin test
        uses: two-pack/redmine-plugin-test-action@add_db_option
        with:
          plugin_name: redmine_auto_assign_group
          redmine_version: ${{ matrix.redmine }}
          ruby_version: ${{ matrix.ruby }}
          database: ${{ matrix.database }}
